import { describe, expect, test } from "bun:test";

import { extractVttText, getVideoId } from "./youtube.ts";

describe("getVideoId", () => {
  test("parses common YouTube URL forms", () => {
    expect(getVideoId("https://www.youtube.com/watch?v=dQw4w9WgXcQ")).toBe(
      "dQw4w9WgXcQ"
    );
    expect(getVideoId("https://youtu.be/dQw4w9WgXcQ?t=12")).toBe("dQw4w9WgXcQ");
    expect(getVideoId("youtube.com/shorts/dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");
    expect(getVideoId("dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");
  });

  test("rejects non-YouTube input", () => {
    expect(getVideoId("https://example.com/watch?v=dQw4w9WgXcQ")).toBe("");
    expect(getVideoId("not a video")).toBe("");
  });
});

describe("extractVttText", () => {
  test("removes VTT metadata, cue timing, and inline tags", () => {
    const vtt = `WEBVTT

NOTE generated by test

1
00:00:00.000 --> 00:00:02.000
<v Speaker>First line</v>

2
00:00:02.000 --> 00:00:04.000
Second <c>line</c>
`;

    expect(extractVttText(vtt)).toBe("First line Second line");
  });
});
